# Generated by Django 4.2.7 on 2023-11-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS_APP', '0002_student_classes_subject_number_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
